"""Data contracts exchanged between the terminal dashboard and the workflow."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

Action = Literal["BUY", "SELL", "HOLD"]
RiskLevel = Literal["LOW", "MEDIUM", "HIGH"]

DISCLAIMER = (
    "Research output only. Not investment advice; verify independently before acting."
)


class AssetQuote(BaseModel):
    """One watchlist row as captured by the terminal dashboard."""

    symbol: str
    kind: str = "stock"
    price: float = 0.0
    change_pct: float = 0.0
    history: list[float] = Field(default_factory=list)


class MarketSnapshot(BaseModel):
    """The dashboard state handed to the workflow for a single analysis pass."""

    generated_at: str
    period_label: str = "7D"
    period_days: int = 7
    assets: list[AssetQuote] = Field(default_factory=list)


class AssetFeatures(BaseModel):
    """Deterministic technical features derived from a quote's price history."""

    symbol: str
    kind: str
    price: float
    change_pct: float
    sma_fast: float
    sma_slow: float
    rsi: float
    momentum_pct: float
    volatility_pct: float
    drawdown_pct: float
    trend: Literal["up", "down", "flat"]


class AssetSignal(BaseModel):
    """Directional read produced by the technical-analyst agent."""

    symbol: str
    action: Action
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str


class TechnicalRead(BaseModel):
    """Structured response contract for the technical-analyst agent."""

    market_note: str
    signals: list[AssetSignal]


class RiskAdjustment(BaseModel):
    """Risk-adjusted version of a single technical signal."""

    symbol: str
    action: Action
    confidence: float = Field(ge=0.0, le=1.0)
    max_position_pct: float = Field(ge=0.0, le=100.0)
    risk_note: str


class RiskReview(BaseModel):
    """Structured response contract for the risk-officer agent."""

    portfolio_risk: RiskLevel
    risk_summary: str
    adjustments: list[RiskAdjustment]


class AdvisoryRow(BaseModel):
    """Per-symbol row rendered by the dashboard signal and detail panels."""

    symbol: str
    action: Action
    confidence: float
    max_position_pct: float
    rationale: str
    risk_note: str
    rsi: float
    sma_fast: float
    sma_slow: float
    momentum_pct: float
    volatility_pct: float
    trend: str


class AdvisoryReport(BaseModel):
    """Final workflow output streamed back to the terminal dashboard."""

    generated_at: str
    mode: Literal["agent", "offline"]
    headline: str
    portfolio_risk: RiskLevel
    market_note: str
    risk_summary: str
    rows: list[AdvisoryRow] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER
    error: str = ""
    kind: Literal["advisory"] = "advisory"


class BacktestRequest(BaseModel):
    """A single-symbol backtest job submitted by the dashboard."""

    symbol: str
    kind_label: str = "stock"
    criteria: str = Field(default="", max_length=500)
    history: list[float] = Field(default_factory=list)
    timestamps: list[float] = Field(default_factory=list)
    initial_capital: float = 10000.0
    frame_delay_ms: int = 40
    max_frames: int = 120


class StrategyPlan(BaseModel):
    """Description of a signal script generated by the Agent Framework agent."""

    name: str
    rationale: str


class GeneratedStrategy(BaseModel):
    """A signal generator's executable, sandboxed strategy proposal."""

    name: str
    rationale: str
    code: str = Field(min_length=1, max_length=20_000)


class Trade(BaseModel):
    """One simulated fill in the backtest."""

    side: Literal["BUY", "SELL"]
    index: int
    time: str
    price: float
    equity: float
    profit_pct: float = 0.0


class BacktestMetrics(BaseModel):
    """Performance statistics for a completed or in-flight backtest."""

    initial_capital: float
    final_value: float
    total_return_pct: float
    cagr_pct: float
    max_drawdown_pct: float
    sharpe: float
    win_rate_pct: float
    exposure_pct: float
    trade_count: int


class BacktestFrame(BaseModel):
    """Incremental progress emitted while the simulation walks the price series."""

    kind: Literal["frame"] = "frame"
    symbol: str
    index: int
    total: int
    time: str
    price: float
    position: int
    equity: float
    drawdown_pct: float
    equity_curve: list[float] = Field(default_factory=list)
    metrics: BacktestMetrics
    trades: list[Trade] = Field(default_factory=list)


class BacktestSummary(BaseModel):
    """Terminal output of the backtest workflow."""

    kind: Literal["summary"] = "summary"
    symbol: str
    mode: Literal["agent", "offline"]
    generated_at: str
    criteria: str = ""
    plan: StrategyPlan
    metrics: BacktestMetrics
    equity_curve: list[float] = Field(default_factory=list)
    trades: list[Trade] = Field(default_factory=list)
    verdict: str = ""
    disclaimer: str = DISCLAIMER
    error: str = ""


class BacktestVerdict(BaseModel):
    """Structured response contract for the backtest-reviewer agent."""

    verdict: str
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)


class AskRequest(BaseModel):
    """A free-form `/ask` question plus the dashboard state that grounds it."""

    question: str
    snapshot: MarketSnapshot | None = None
    focus_symbol: str = ""


class AskAnswer(BaseModel):
    """Structured response contract for the market-analyst agent."""

    answer: str
    highlights: list[str] = Field(default_factory=list)


class AskReply(BaseModel):
    """Answer to one `/ask` question, streamed back to the dashboard."""

    kind: Literal["ask"] = "ask"
    generated_at: str
    mode: Literal["agent", "offline"]
    question: str
    answer: str
    highlights: list[str] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER
    error: str = ""


class ModelRequest(BaseModel):
    """A `/model` command: inspect the active backend or switch to another one.

    `api_key_var` names an environment variable; a literal key is never accepted
    so secrets stay out of the terminal and the request log.
    """

    action: Literal["status", "set"] = "status"
    provider: str = ""
    model: str = ""
    endpoint: str = ""
    api_key_var: str = ""


class ModelStatus(BaseModel):
    """Description of the active chat backend, with no secret material."""

    kind: Literal["model"] = "model"
    provider: str
    model: str = ""
    endpoint: str = ""
    mode: Literal["agent", "offline"]
    available: list[str] = Field(default_factory=list)
    usage: dict[str, str] = Field(default_factory=dict)
    default_api_key_var: str = ""
    error: str = ""
